version: '3.8'
services:
  discovery-server:
    build:
      context: ./services/discoveryserver
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - hrm-network

  api-gateway:
    build:
      context: ./services/apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - discovery-server
      - employee-service
    networks:
      - hrm-network
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka
      - EMPLOYEE_SERVICE_URL=http://employee-service:9001

  employee-service:
    build:
      context: ./services/employeeservice
      dockerfile: Dockerfile
    container_name: employee-service
    ports:
      - "9001:9001"
    depends_on:
      - discovery-server
      - axon-server
    volumes:
      - ./services/employeeservice/src/main/resources/EmployeeServiceAccessKey.json:/app/src/main/resources/EmployeeServiceAccessKey.json
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka
      - AXON_SERVER_HOST=axon-server
      - AXON_SERVER_PORT=8124
      - FIREBASE_CONFIG_PATH=/app/src/main/resources/EmployeeServiceAccessKey.json
    networks:
      - hrm-network

  axon-server:
    image: axoniq/axonserver
    container_name: axon-server
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    networks:
      - hrm-network

networks:
  hrm-network:
    driver: bridge
