// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW-WpOCvCdEXeCBgvp2RVZxgjeYwOWG1o',
    appId: '1:220250884125:web:f2c5d62e92f2e3f8725ef4',
    messagingSenderId: '220250884125',
    projectId: 'hrm-application-auth-firebase',
    authDomain: 'hrm-application-auth-firebase.firebaseapp.com',
    storageBucket: 'hrm-application-auth-firebase.firebasestorage.app',
    measurementId: 'G-7YMNQQRDPR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzjAfcKHVZ34nyQIt2PXnPisYfoTC2avM',
    appId: '1:220250884125:ios:fc2c1cd3c4360273725ef4',
    messagingSenderId: '220250884125',
    projectId: 'hrm-application-auth-firebase',
    storageBucket: 'hrm-application-auth-firebase.firebasestorage.app',
    iosClientId: '220250884125-i9jmjkaid089ul486erdhhure62dmunk.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrmApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzjAfcKHVZ34nyQIt2PXnPisYfoTC2avM',
    appId: '1:220250884125:ios:fc2c1cd3c4360273725ef4',
    messagingSenderId: '220250884125',
    projectId: 'hrm-application-auth-firebase',
    storageBucket: 'hrm-application-auth-firebase.firebasestorage.app',
    iosClientId: '220250884125-i9jmjkaid089ul486erdhhure62dmunk.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrmApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW-WpOCvCdEXeCBgvp2RVZxgjeYwOWG1o',
    appId: '1:220250884125:web:33308ce3625a54f5725ef4',
    messagingSenderId: '220250884125',
    projectId: 'hrm-application-auth-firebase',
    authDomain: 'hrm-application-auth-firebase.firebaseapp.com',
    storageBucket: 'hrm-application-auth-firebase.firebasestorage.app',
    measurementId: 'G-79F0BPWLDP',
  );
}
