spring:
  application:
    name: employee_service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: employee-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

axon:
  axonserver:
    servers: ${AXON_SERVER_HOST}:${AXON_SERVER_PORT}
    context: default
