spring:
  application:
    name: employeeservice

    
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

#axoniq:
#  console:
#    application-name: Employee_Service
#    credentials: fc950d54-0:c30062b0dc7e43d2829d5221cb16be17
#    dlq-mode: FULL

#axon:
#  serializer:
#    general: jackson
#    events: jackson
#    messages: jackson

axon:
  axonserver:
    servers: ${AXON_SERVER_HOST}:${AXON_SERVER_PORT}
    context: default


#debug: true