spring:
  application:
    name: employee_service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: employee-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

axon:
  axonserver:
    servers: ${AXON_SERVER_HOST}:${AXON_SERVER_PORT}
    context: default
