spring:
  application:
    name: employeeservice

    
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#axon:
#  axonserver:
#    servers:
#      - name: local
#        hostname: localhost
#        port: 8024


#debug: true