server:
  port: 9000 

spring:
  application:  
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employeeservice
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/employee/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:  
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
