server:
  port: 9000

spring:
  application:  
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/employee/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:  
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
