spring:
  application:
    name: recruitment_service

    
server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

axon:
  axonserver:
    servers: ${AXON_SERVER_HOST}:${AXON_SERVER_PORT}
    context: default