class EmployeeInf {
  final String name;
  final String role;
  final String mail;
  final String mobile;
  final String department;
  final String manager;
  final bool isManager;
  final String? workLocation;
  final String? schedule;
  final String? salaryStructure;
  final String? contractType;
  final double? cost;
  final String? personalAddress;
  final String? personalMail;
  final String? personalMobile;
  final String? relativeName;
  final String? relativeMobile;
  final String? certification;
  final String? school;
  final String? maritalStatus;
  final int? child;
  final String? nationality;
  final String? idNum;
  final String? ssNum;
  final String? passport;
  final String? sex;
  // final DateTime? birthDate;
  final String? birthDate;
  final String? birthPlace;
  static final List<String> defaultWorkLocations = ['Office', 'Home'];
  static final List<String> defaultCertifications = ['Graduated', 'Bachelor', 'Master', 'Doctor'];
  static final List<String> defaultMaritalStatus = ['Single', 'Married', 'Legal Cohabitant','Divorced', 'Widower'];
  static final List<String> defaultSex = ['Male', 'Female'];

  EmployeeInf({
    required this.name,
    required this.role,
    required this.mail,
    required this.mobile,
    required this.department,
    required this.manager,
    required this.isManager,
    this.workLocation,
    this.schedule,
    this.salaryStructure,
    this.contractType,
    this.cost,
    this.personalAddress,
    this.personalMail,
    this.personalMobile,
    this.relativeName,
    this.relativeMobile,
    this.certification,
    this.school,
    this.maritalStatus,
    this.child,
    this.nationality,
    this.idNum,
    this.ssNum,
    this.passport,
    this.sex,
    this.birthDate,
    this.birthPlace,
  });
}

  int countEmployeesInDepartment(List<EmployeeInf> employees, String department) {
    return employees.where((employee) => employee.department == department).length;
  }

  List<String> getManagers(List<EmployeeInf> employees) {
    return employees.where((employee) => employee.isManager).map((e) => e.name).toList()..sort((a, b) => a.compareTo(b));
  }

final List<EmployeeInf> employees = [
  //Administration
  EmployeeInf(
    name: 'Son Tung MTP',
    role: 'Director',
    mail: 'sontung@gmail.com',
    mobile: '123-456-7890',
    department: 'Administration',
    manager: 'Phuong Hang',
    isManager: true,
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',
    salaryStructure: 'Employee',
    contractType: 'Permanent',
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
    certification: 'Flutter', 
    school: 'University of California', 
    maritalStatus: 'Married', 
    child: 2, 
    nationality: 'USA', 
    idNum: '123456789', 
    ssNum: '987654321', 
    passport: 'password', 
    sex: 'Male', 
    // birthDate: DateTime(2000, 08, 11), 
    birthDate: '2000-08-11',
    birthPlace: 'California',
  ),
  EmployeeInf(
    name: 'Phuong Hang',
    role: 'CEO',
    mail: 'phuonghang@gmail.com',
    mobile: '890-123-4567',
    department: 'Administration',
    manager: 'Phuong Hang',
    isManager: true,
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Dat G',
    role: 'Secretary',
    mail: 'vosu@gmail.com',
    mobile: '123-456-7890',
    department: 'Administration',
    manager: 'Son Tung MTP',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'HieuThuHai',
    role: 'Database Administrator',
    mail: 'babyboo@gmail.com',
    mobile: '123-456-7890',
    department: 'Administration',
    manager: 'Son Tung MTP',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  //Research & Development
  EmployeeInf(
    name: 'Jack J97',
    role: 'Project Manager',
    mail: '5tr@gmail.com',
    mobile: '234-567-8901',
    department: 'Research & Development',
    manager: 'Son Tung MTP',
    isManager: true,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Huong Tit',
    role: 'Dev',
    mail: 'kth@gmail.com',
    mobile: '345-678-9012',
    department: 'Research & Development',
    manager: 'Jack J97',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Hieu PC',
    role: 'Dev',
    mail: 'hieupc@gmail.com',
    mobile: '456-789-0123',
    department: 'Research & Development',
    manager: 'Jack J97',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Andree RH',
    role: 'Designer',
    mail: 'lefthand@gmail.com',
    mobile: '123-456-7890',
    department: 'Research & Development',
    manager: 'Jack J97',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Decao CG',
    role: 'Actuary',
    mail: 'lamminh@gmail.com',
    mobile: '123-456-7890',
    department: 'Research & Development',
    manager: 'Jack J97',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Minh Tien',
    role: 'Collaborator',
    mail: 'tandien@gmail.com',
    mobile: '123-456-7890',
    department: 'Research & Development',
    manager: 'Jack J97',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Part-time 25 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  //HR
  EmployeeInf(
    name: 'Chau Bui',
    role: 'HR',
    mail: 'chaubui@gmail.com',
    mobile: '678-901-2345',
    department: 'Human Resources',
    manager: 'Son Tung MTP',
    isManager: true,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Dam Tong',
    role: 'HR',
    mail: 'ngoclinh@gmail.com',
    mobile: '789-012-3456',
    department: 'Human Resources',
    manager: 'Chau Bui',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  //Sales
  EmployeeInf(
    name: 'Tran Thanh',
    role: 'Content Creator',
    mail: 'mrcry@gmail.com',
    mobile: '901-234-5678',
    department: 'Sales',
    manager: 'Son Tung MTP',
    isManager: true,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Chi Pu',
    role: 'Content Creator',
    mail: 'cbc@gmail.com',
    mobile: '012-345-6789',
    department: 'Sales',
    manager: 'Tran Thanh',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Trung Tin',
    role: 'Collaborator',
    mail: 'trungtin@gmail.com',
    mobile: '123-456-7890',
    department: 'Sales',
    manager: 'Tran Thanh',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Part-time 25 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Thang Ngot',
    role: 'Sales',
    mail: 'nhactamda@gmail.com',
    mobile: '123-456-7890',
    department: 'Sales',
    manager: 'Tran Thanh',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Truong Giang',
    role: 'Sales',
    mail: 'hetai@gmail.com',
    mobile: '123-456-7890',
    department: 'Sales',
    manager: 'Tran Thanh',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  //Accounting
  EmployeeInf(
    name: 'Chi Long',
    role: 'Accountant',
    mail: 'mck@gmail.com',
    mobile: '123-456-7890',
    department: 'Accounting',
    manager: 'Son Tung MTP',
    isManager: true,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  //Quality
  EmployeeInf(
    name: 'Thinh Noo',
    role: 'Quality Assurance',
    mail: 'noo@gmail.com',
    mobile: '234-567-8901',
    department: 'Quality',
    manager: 'Son Tung MTP',
    isManager: true,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  EmployeeInf(
    name: 'Ngoc Thy',
    role: 'Tester',
    mail: 'victoria@gmail.com',
    mobile: '567-890-1234',
    department: 'Quality',
    manager: 'Thinh Noo',
    isManager: false,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
  //Financial
  EmployeeInf(
    name: 'Obito',
    role: 'Business Analysis',
    mail: 'vstra@gmail.com',
    mobile: '123-456-7890',
    department: 'Financial',
    manager: 'Son Tung MTP',
    isManager: true,  
    workLocation: 'Office',
    schedule: 'Standard 40 hours/week',  
    salaryStructure: 'Employee',
    contractType: 'Permanent',  
    cost: 25.0000,  
    personalAddress: 'HCM',
    personalMail: 'sontung@gmail.com',
    personalMobile: '123-456-7890',
    relativeName: 'Dat G',
    relativeMobile: '987-654-3210',  
  ),
];
