name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
   
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Build Flutter app
        run: |
          cd frontend
          flutter build apk --release
